apiVersion: acme.com/v1
kind: Postgres
metadata:
  name: voting-database
  namespace: acme-operators
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: voting-app-backend
  namespace: acme-operators
route: /api(/|$)(.*)
rewrite: /$2
image: kind-registry:5001/voting-app-backend:latest
replicas: 1
port: 3000
env:
  POSTGRES_HOST: ${{ kblock://postgres.acme.com/voting-database/host }}
  POSTGRES_PORT: ${{ kblock://postgres.acme.com/voting-database/port }}
  POSTGRES_USER: ${{ kblock://postgres.acme.com/voting-database/user }}
  POSTGRES_DB: ${{ kblock://postgres.acme.com/voting-database/database }}
envSecrets:
  POSTGRES_PASSWORD:
    name: ${{ kblock://postgres.acme.com/voting-database/passwordSecret }}
    key: ${{ kblock://postgres.acme.com/voting-database/passwordKey }}