apiVersion: acme.com/v1
kind: Postgres
metadata:
  name: voting-database
  namespace: acme-operators
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: voting-app-backend
  namespace: acme-operators
image: localhost:5001/voting-app-backend:latest
replicas: 1
port: 3000
env:
  POSTGRES_HOST: ${{ kblock://postgres.acme.com/voting-database/host }}
  POSTGRES_PORT: ${{ kblock://postgres.acme.com/voting-database/port }}
  POSTGRES_USER: ${{ kblock://postgres.acme.com/voting-database/user }}
  POSTGRES_DB: ${{ kblock://postgres.acme.com/voting-database/database }}
envSecrets:
  POSTGRES_PASSWORD:
    name: ${{ kblock://postgres.acme.com/voting-database/passwordSecret }}
    key: ${{ kblock://postgres.acme.com/voting-database/passwordKey }}
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: voting-cast-app
  namespace: acme-operators
image: localhost:5001/voting-cast-app:latest
replicas: 1
port: 5173
env: 
  VITE_SERVER_URL: ${{ kblock://workload.acme.com/voting-app-backend/host }}
  VITE_SERVER_PORT: ${{ kblock://workload.acme.com/voting-app-backend/port }}
command: ["npm", "run", "dev"]