apiVersion: acme.com/v1
kind: Postgres
metadata:
  name: voting-database
  namespace: acme-operators
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: voting-app-backend
  namespace: acme-operators
route: /api(/|$)(.*)
rewrite: /$2
image: kind-registry:5001/voting-app-backend:latest
replicas: 1
port: 3000
env:
  POSTGRES_HOST: ${{ kblock://postgres.acme.com/voting-database/host }}
  POSTGRES_PORT: ${{ kblock://postgres.acme.com/voting-database/port }}
  POSTGRES_USER: ${{ kblock://postgres.acme.com/voting-database/user }}
  POSTGRES_DB: ${{ kblock://postgres.acme.com/voting-database/database }}
envSecrets:
  POSTGRES_PASSWORD:
    name: ${{ kblock://postgres.acme.com/voting-database/passwordSecret }}
    key: ${{ kblock://postgres.acme.com/voting-database/passwordKey }}
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: vote-casting-app
  namespace: acme-operators
image: kind-registry:5001/vote-casting-app:latest
route: /vote
replicas: 1
port: 5173
env: 
  VITE_SERVER_URL: http://localhost
  VITE_SERVER_PORT: "80"
command: ["npm", "run", "dev"]
---
apiVersion: acme.com/v1
kind: Workload
metadata:
  name: votes-results-app
  namespace: acme-operators
image: kind-registry:5001/votes-results-app:latest
route: /results
replicas: 1
port: 5174
env: 
  VITE_SERVER_URL: http://localhost
  VITE_SERVER_PORT: "80"
command: ["npm", "run", "dev"]